import Foundation

let closeGoodByeAndOut = "wamp.close.goodbye_and_out"
let closeCloseRealm = "wamp.close.close_realm"
let closeSystemShutdown = "wamp.close.system_shutdown"
let closeKilled = "wamp.close.killed"

let errNoMatchingAuthMethod = "wamp.error.no_matching_auth_method"
let errNoSuchRealm = "wamp.error.no_such_realm"
let errNoSuchRole = "wamp.error.no_such_role"
let errNoSuchPrincipal = "wamp.error.no_such_principal"
let errNoSuchSession = "wamp.error.no_such_session"
let errAuthenticationDenied = "wamp.error.authentication_denied"
let errAuthenticationFailed = "wamp.error.authentication_failed"
let errAuthenticationRequired = "wamp.error.authentication_required"
let errAuthorizationDenied = "wamp.error.authorization_denied"
let errAuthorizationFailed = "wamp.error.authorization_failed"
let errAuthorizationRequired = "wamp.error.authorization_required"
let errTimeout = "wamp.error.timeout"
let errOptionNotAllowed = "wamp.error.option_not_allowed"
let errOptionDisallowedDiscloseMe = "wamp.error.option_disallowed.disclose_me"
let errNetworkFailure = "wamp.error.network_failure"
let errUnavailable = "wamp.error.unavailable"
let errNoAvailableCallee = "wamp.error.no_available_callee"
let errFeatureNotSupported = "wamp.error.feature_not_supported"
let errInvalidURI = "wamp.error.invalid_uri"
let errNoSuchProcedure = "wamp.error.no_such_procedure"
let errProcedureAlreadyExists = "wamp.error.procedure_already_exists"
let errNoSuchRegistration = "wamp.error.no_such_registration"
let errNoSuchSubscription = "wamp.error.no_such_subscription"
let errInvalidArgument = "wamp.error.invalid_argument"
let errCanceled = "wamp.error.canceled"
let errPayloadSizeExceeded = "wamp.error.payload_size_exceeded"
let errProtocolViolation = "wamp.error.protocol_violation"
let errNotAuthorized = "wamp.error.not_authorized"
